### ISSUE TITLE
[Bug]: Unable to build OpenRV with cmake 3.26.0

### ISSUE THREAD

**Issue by geffrak** [AcademySoftwareFoundation/OpenRV#100]
### What happened?

New contributors cannot build OpenRV if their build toolchain is too recent. It seems like 
ADD_COMPILE_OPTIONS contains -std=${_clang_cxx_standard}, and it's illegal in C.

### List all the operating systems versions where this is happening

MacOS

### On what computer hardware is this happening?

Any

### Relevant console log output

```shell
[...]
error: invalid argument '-std=c++17' not allowed with 'C'
[...]
```

### Extra information

Repro Step:
$ cmake --build _build/ --target resample --verbose 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Volutionn** [comment]
Just flagging I'm facing the same issue, unable to build OpenRV on macOS.
