### ISSUE TITLE
Missing Accreditation

### ISSUE THREAD

**Issue by blackencino** [AcademySoftwareFoundation/OpenRV#11]
Hi, my name is Chris Horvath, and I am one of the original founders of Tweak Films, which became Tweak Software, which created RV, and which was eventually purchased by Autodesk.

This repository contains some code that is mostly unmodified from the original Twk libraries, which were written by Jim Hourihan, Mike Root, and me from the years 2001-2004. As an example, `base/TwkMath/Vec3.h` is virtually unchanged from 2001, as are many parts of TwkMath, TwkUtil, TwkImage. There are dozens of talented artists and engineers who contributed to this codebase over the years, as part of Tweak or Autodesk. On one hand, I'm proud to see this work find its way into an ASWF proposal. On the other hand, it is plainly heartbreaking that none of the names of the many artists and programmers who made up Tweak over its years are attributed, and that Tweak is not attributed at all, except in copyright banners.

I don't in any way dispute the ownership of this code, it belongs to Autodesk as a result of their purchase of Tweak Software. I also don't claim authorship of RV, which was crafted into a product after my time at Tweak. However, please add the names of the many contributors to the Tweak codebase to the "Contributors.md" file, and some mention of the history of the code and product.

**Comment by travisbutton** [comment]
I'll chime in here and say as someone who has been using RV since its inception, that I think the best versions (with the exception of ProRes support) were released under Tweak prior to the Autodesk acquisition. They essentially ruined it when it was folded into Shotgun but luckily we already had some permanent standalone licenses that we can still utilize to this day without Shotgrid. Happy to see it begin a journey of being open sourced as a standalone application.

**Comment by guillaume-brossard** [comment]
@blackencino Hi Chris, thanks for voicing up. We are working on something. Would you mind reaching out by email so we can discuss the approach?

**Comment by rubikstriangle** [comment]
As a nod to tweak, is there any chance we can restore the old RV logo?  I became kind of fond of it over the years.  If not the original logo, perhaps a variant of the RV with the door open signifying that RV is now open?
