### ISSUE TITLE
[Bug]: gltext memory leak

### ISSUE THREAD

**Issue by skyyred** [AcademySoftwareFoundation/OpenRV#120]
Using gltext seems to cause a memory leak issue.  
I provided an example mode that creates a watermark using gltext that shows the issue, however it seems to also happen with the Color Inspecter tool shipped with Openrv (uses gltext).  Memory usage of RV will continue to increase causing RV to slow down and or eventually crash.

Repo:
copy provided ttf file to /var/tmp/
install provided RV package
Launch RV
Open provided image sequence 'smaple_image.1-10#.jpg'
Play 10 frames in loop playback
'top' cmd shows RES stable around 1121M
hit 'o' hot key to toggle 'memoryleak' mode
'top' cmd shows RES steadily increases over time.
[memory_leak_example.zip](https://github.com/AcademySoftwareFoundation/OpenRV/files/11324764/memory_leak_example.zip)

### List all the operating systems versions where this is happening

Centos7

### On what computer hardware is this happening?

Quadro P5000

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by savoiei** [comment]
Hi skyrred, I had a look at this case yesterday and this morning and, while I did not reproduce the issue with the Color Inspector yet, I could see the problem on my side thanks to your package. Also, thank you so much for the clear repro steps and taking the time of creating that package! It is really appreciated!
