### ISSUE TITLE
Problem in WIn 11

### ISSUE THREAD

**Issue by cgdestroyer** [AcademySoftwareFoundation/OpenRV#13]
I tried last step to Invoke CMake from an MSYS2-MinGW64 shell 

`cmake -B cmake-build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DRV_DEPS_WIN_PERL_ROOT=/c/Strawberry/perl/bin -DRV_DEPS_QT5_LOCATION=/c/Qt/Qt5.15.2/msvc2019_64
cmake --build cmake-build --config Release --target rv -j8 
cmake --install cmake-build --config Release`

and got this error:

`CMake Error at src/lib/mu/MuQt5/CMakeLists.txt:10 (FIND_PACKAGE):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "C:/OpenRV/cmake-build/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: rv.vcxproj
CMake Error: Error processing file: C:/OpenRV/cmake-build/cmake_install.cmake
`
any idea what am I doing wrong?

**Comment by rogernelson** [comment]
Hi @cgdestroyer.  The error means that CMake could not find Qt in the location specified by your cmake command /c/Qt/Qt5.15.2/msvc2019_64 which is equivalent to c:\Qt\Qt5.15.2\msvc2019_64.  Do you have Qt installed in that path?

**Comment by cgdestroyer** [comment]
Thank you @rogernelson it turned out that i had "qt" before 5.15.2 and on my system was just numbers, now it works great, thank you for help, I was blind for such obvious and simple problem, need some sleep :)
cheers! :)

**Comment by rogernelson** [comment]
Excellent! I am very happy you got it working.

**Comment by rogernelson** [comment]
Also to make things easier, if everything is installed in default locations you can do `source rvmds.sh` and the `rvmk` to set up all the variables for you automatically (you can also override the locations by setting envars).

**Comment by cgdestroyer** [comment]
Unfortunately got some more errors in last step and don't know why :/ 

https://i.imgur.com/rsKDG94.jpg
https://i.imgur.com/uTC5XFO.jpg
https://i.imgur.com/1txPibU.jpg
https://i.imgur.com/v5RdIZ3.jpg
https://i.imgur.com/mxwDhrJ.jpg
https://i.imgur.com/H0N61Tv.jpg

**Comment by rogernelson** [comment]
Do you have VS2022 on the machine? It looks like it's trying to use VS2022 to compile boost (a third party dependency) which unfortunately boost does not support.

**Comment by cgdestroyer** [comment]
yes I have VS 2022, 2019 and 2017, should I uninstall 2022 one? and left only other two

**Comment by rogernelson** [comment]
If you don't need it I think that would be the easiest option.  The only alternative I can think of would be to investigate if there's some way to force boost to use a particular version of MSVC, but that would require some time to dig into it.

**Comment by cgdestroyer** [comment]
Thank you for your answers. I uninstalled VS 2022, but it wasn't it.
I had installed VS 2019 community and 2017 Team because there was no community version on Microsoft downloads page.
https://i.imgur.com/bzWlhKb.jpg
I found VS  2017 Community installer on techspot.com webpage and uninstalled team explorer and installed Community
https://i.imgur.com/NlzD90p.jpg

added additional libraries but portably it was unnecessary 
https://i.imgur.com/5N60rSm.jpg
https://i.imgur.com/5C4Cld2.jpg
 
And now cmake in MSYS2 MINGW64 works for about 12minutes other than 2min like before and only error I got at the beginning was this 
https://i.imgur.com/ooIy7ni.jpg

and some warnings
https://i.imgur.com/W2zTjaI.jpg
https://i.imgur.com/Hup8EPB.jpg

and this how it ended 
https://i.imgur.com/quurBA8.jpg

I was it? Thats's all? I don't see any OpenRV exe file or something I can use so there are still some problems with that?

**Comment by rogernelson** [comment]
I don't see the same errors from before, so at least you got a bit further.  Another user got that same aclocal error you're seeing in issue https://github.com/AcademySoftwareFoundation/OpenRV/issues/3.

He started from a clean machine and was able to get it to build, so it's definitely something installed on the machine that is causing the error, but we were unfortunately able to find what it was.

**Comment by cgdestroyer** [comment]
Tried virtual machine, have win 11 and only nessery things installed and got this error :/

https://i.imgur.com/nWgZlOF.jpg

**Comment by rogernelson** [comment]
Closing this thread since we have two threads (also https://github.com/AcademySoftwareFoundation/OpenRV/issues/27) going with the same errors.  It will be easier to follow-up if there is just one.
