### ISSUE TITLE
#include <sys/sysctl.h>  deprecated from glibc on recent distros add conditional import that only runs if the distro is old enough.

### ISSUE THREAD

**Issue by NicTanghe** [AcademySoftwareFoundation/OpenRV#20]
#include <sys/sysctl.h>  Deprecated from glibc on EL9.

Please add conditional statement that checks how recent your system is to OpenRV/src/lib/base/TwkUtil/SystemInfo.cpp,

**Comment by NicTanghe** [comment]
I`m not a c++ dev but I`ll c if i can make something.

**Comment by rogernelson** [comment]
I checked on CentOS7 and it compiles fine without the line.  Mac needs it though, even on the most recent Ventura build.  

So I would suggest replacing the `else` on this line: https://github.com/AcademySoftwareFoundation/OpenRV/blob/ffa546969c13f88ebe405f087eb9bd4a1b69d2d9/src/lib/base/TwkUtil/SystemInfo.cpp#L21

with:
```
#elif __APPLE__
```
If you'd rather I do the PR, I can take care of it.

**Comment by rogernelson** [comment]
There's a PR in review now that should solve this for you.  I built it successfully on Mac Ventura 13.1  and CentOS7.

**Comment by NicTanghe** [comment]
THX !
