### ISSUE TITLE
Windows 10 Build Error -  Can't find atomic_ops.h

### ISSUE THREAD

**Issue by jonassorgenfrei** [AcademySoftwareFoundation/OpenRV#21]
I tried Compling openRV with VS 2019 as explained in the build instructions and followed the build instructions completly.

Unfortunatly i got the error that atomic_ops.h in gc_priv.h any idea what i might did wrong/misconfigured?

Additionally i had the same issue as described here in #5 but for the moment just replaced --only-matching with -o what was helping for the moment.

**Comment by rogernelson** [comment]
In the case it was because the user also had `wsl` installed and the grep from `wsl` was slightly different from the grep from msys and the `wsl` version was being found first. Do you also have `wsl` installed?

**Comment by jonassorgenfrei** [comment]
Yeah thats probably the issue with the grep operation but I was more wondering about:
atomic_ops.h in gc_priv.h. 

Is this a system header or is this coming from anl 3rd party library?

**Comment by rogernelson** [comment]
They are both coming from thirdparties,` atomic_ops` and `gc` respectively (you can find the cmake files for both in `cmake/dependenices`).  If the error is that they could not be found, perhaps there was a problem downloading/building/installing those?  Do you have any build errors related to those?
