### ISSUE TITLE
[Bug]: otio plugin fails to export otio file with nested Sequences

### ISSUE THREAD

**Issue by skyyred** [AcademySoftwareFoundation/OpenRV#214]
### What happened?

OpenRV fails to export otio for your session when you have nested SequenceGroups i.e. Nested Compositions in OTIO. 

Repo:
create 2 new sources you can use the generate colorbar option in Session Manager
remove those 2 new sources from "Default Sequence"
select the 2 new sources and create a new Sequence
add the new Sequences create to "Default Sequence"
File > Export > OTIO File...

![otio_plugin](https://github.com/AcademySoftwareFoundation/OpenRV/assets/47487911/433cc425-c2ef-4934-a3d5-7c4c728baa1d)

### List all the operating systems versions where this is happening

cent7

### On what computer hardware is this happening?

any

### Relevant console log output

```shell
Traceback (most recent call last):
  File "../plugins/Python/otio_reader_plugin.py", line 150, in otio_export
    event.contents()
  File "../plugins/Python/otio_writer.py", line 53, in write_otio_file
    otio_root = create_otio_from_rv_node(root_node_name, timeline=timeline)
  File "../plugins/Python/otio_writer.py", line 107, in create_otio_from_rv_node
    result = create_type_map[node_type](node_name, *args, **kwargs)
  File "../plugins/Python/otio_writer.py", line 197, in _create_track
    cut_in_frame=cut_in_frame,
  File "../plugins/Python/otio_writer.py", line 107, in create_otio_from_rv_node
    result = create_type_map[node_type](node_name, *args, **kwargs)
TypeError: _create_track() got an unexpected keyword argument 'in_frame'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rogernelson** [comment]
Thanks for the report.  I will have a look at this.
