### ISSUE TITLE
UI styles and fonts?

### ISSUE THREAD

**Issue by BrianHanke** [AcademySoftwareFoundation/OpenRV#23]
Howdy all, I'm curious what controls the UI styles (buttons, icons, colors) and interface fonts in OpenRV. Are these things that have to be set before building or are there scripts to customize post-build? I found rvui which controls some font sizes and UI colors, but it seems limited. Thank you!

**Comment by NicTanghe** [comment]
the snapping of the draw panel excs.autodesk does realy well. It would be nice if i didn’t feel like i was running openRV in 2008.

**Comment by BrianHanke** [comment]
Yeah the UI is super dated. Seems like it would be simple to update some icons, change some colors and fonts, but I'm not sure where to start. I found some font-related code but it didn't make any sense to me. I was hoping there'd be a Qt style sheet somewhere...

**Comment by marcomeyerVFX** [comment]
you can pass stylesheets through the CLI

![image](https://user-images.githubusercontent.com/10450137/213895649-51bac9b2-e47a-4243-b24d-a694c5a07727.png)

**Comment by BrianHanke** [comment]
Oh sweet, thanks! Will be fun to modernize it a bit. It's already an improvement just feeding it a blank CSS to get a default Windows UI.

**Comment by geffrak** [comment]
If you are ok @BrianHanke, I will close this issue. Please re-open it if there's still an issue.
