### ISSUE TITLE
[Bug]: rvio crashes when loading .rv files saved from branch ocio-update-to-v2 and active OCIO settings

### ISSUE THREAD

**Issue by stefanke** [AcademySoftwareFoundation/OpenRV#260]
### What happened?

We are using the ocio-update-to-v2 branch to enable OCIO v2 in our pipeline. Inside RV everything works using the original package "ocio_source_setup-2.5.rvpk". We specify our custom config file using "rv_ocio_setup.py" and can enable the correct File Color Space and Displays. 

We are using the ftrack-review plugin for approvals/changes. The steps in the ftrack-review plugin are:
- annotate frames with the annotation tool within rv
- Add a note and submit

The ftrack plugin then takes over with the following steps:

- save an .rv file from the rv session in a temp folder (i.e. temp_207624_3.rv)
- Load this .rv file via an rvio command in the background to create JPGs with the following command:
   /opt/rv/bin/rvio_sw -v -err-to-out /tmp/temp_207624_3.rv -o /tmp/56ec6d10-562b-11ee-94ea-001b21c207b8_#.jpg -t 40 -overlay frameburn 0.8 1.0 30.0
- Upload the jpg to ftrack via the API

The rvio command crashes with a segmentation fault, so no jpg is written. The terminal output is:

Version 1.0.0, built on Aug 31 2023 at 21:29:00 (HEAD=b93a3f8).
Copyright Contributors to the Open RV Project
INFO: reading version 4 session file format
INFO: loading /stornext/PROJECTS/pipeline/client/project/40_2d/20_nuke/output/shots/XXX_105028_070/COMP/XXX_105028_070_COMP_v009/MAIN/exr/XXX_105028_070_COMP_MAIN_v009.%04d.exr
Segmentation fault (core dumped)

What I tried:
- When I deactivate the File Color Space and Display settings in the OCIO plugin before submitting the notes everything works. But then the submitted images are not in the correct color space. 
- When I edit the rv file and remove all OCIO entries everything works

I think rvio crashes because of the OCIO entries in the .rv file. 

I can load the .rv file into rv player and everything works.

Altough we are using the ftrack-5.0.rvpkg package this is not a problem of this package. We can replicate the behaviour saving to a .rv file ourselves and using rvio manually with the comandline shown above.

### List all the operating systems versions where this is happening

Rocky Linux 8.8

### On what computer hardware is this happening?

Lenovo P620, Threadripper Pro 3995WX, 64 Cores, 250GB Memory, Nvidia RTX A5000 GFX

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tbabiin** [comment]
Hi @stefanke , thank you for reporting this issue! Your repro steps helped us repro'ing quickly.
However, one question: adding the OCIO Environment variable fixes the crash. Does your code have the OCIO variable set when calling rvio?

**Comment by stefanke** [comment]
We do not have the OCIO environment variable set globally because of conflicts in our different DCCs. 
When I set the environment variable and run the rvio command again everything works as expected.

For now this helps us as a workaround, thanks! Anyway, it would be perfect if this can be fixed in the future?

Thanks for your help,
Stefan
