### ISSUE TITLE
Compiling PySide keeps downloading libclang.7z when archive has no CRC

### ISSUE THREAD

**Issue by johhnry** [AcademySoftwareFoundation/OpenRV#28]
When compiling PySide on Linux, the archive `libclang.7z` is downloaded from an url and used as part of the build:

https://github.com/AcademySoftwareFoundation/OpenRV/blob/41eccbe03bf2462b399fec6511be1d11de6c6327/src/build/make_pyside.py#L86

I have an error further during the build so I tried running cmake again but it kept redownloading `libclang.7z` even thought the file is still there.

I found that the issue was that it's checking the integrity of the 7z file with the [`SevenZipFile.test()`](https://py7zr.readthedocs.io/en/latest/api.html#py7zr.SevenZipFile.test) function here:

https://github.com/AcademySoftwareFoundation/OpenRV/blob/41eccbe03bf2462b399fec6511be1d11de6c6327/src/build/make_pyside.py#L88

In my case I don't know why the downloaded archive doesn't have any CRC record but the archive is not corrupted, therefore returning `None` and evaluating it to `False`.

A fix is to explicitly check if `False`:

```python
if os.path.exists(libclang_zip) is False:
    download_file(libclang_url, libclang_zip)
# if we have a failed download, clean it up and redownload.
elif verify_7z_archive(libclang_zip) is False:
    os.remove(libclang_zip)
    download_file(libclang_url, libclang_zip)
```

**Comment by geffrak** [comment]
Hi @johhnry, would you mind making a Pull Request about that one?
