### ISSUE TITLE
 Windows 10: cmake/macros/rv_stage.cmake:406 (EXECUTE_PROCESS)

### ISSUE THREAD

**Issue by AnhTuWally** [AcademySoftwareFoundation/OpenRV#32]
Hi, 

I've been following the instruction from this link

https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/doc/build_system/config_windows.md

I get to this stage and get some error. 

cmake -B cmake-build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DRV_DEPS_WIN_PERL_ROOT=/c/Strawberry/perl/bin -DRV_DEPS_QT5_LOCATION=/c/Qt/Qt5.15.11/5.15.11/msvc2019_64

In particular, I get:
```

CMake Error at cmake/macros/rv_stage.cmake:406 (EXECUTE_PROCESS):
  EXECUTE_PROCESS failed command indexes:

    1: "Child return code: 1"

Call Stack (most recent call first):
  src/plugins/rv-packages/additional_nodes/CMakeLists.txt:11 (RV_STAGE)
```
  
  
If I go to cmake/macros/rv_stage.cmake and comment everything inside out, I was able to finish the building and installing process. However, there was no rv.exe found in the final installation. Please advise.

**Comment by AnhTuWally** [comment]
Hi @geffrak, thank you for your quick response. Here are the lines before:

`-- Build type: Release
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- Building RV for Microsoft Windows
-- Using build branch: main
-- Using build hash: a2d76d5
-- RV_STAGE_ROOT_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app
-- RV_STAGE_BIN_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/bin
-- RV_STAGE_LIB_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/lib
-- RV_STAGE_INCLUDE_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/include
-- RV_STAGE_SRC_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/src
-- RV_STAGE_RESOURCES_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/resources
-- RV_STAGE_PLUGINS_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns
-- RV_STAGE_PLUGINS_CONFIGFILES_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/ConfigFiles
-- RV_STAGE_PLUGINS_IMAGEFORMATS_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/ImageFormats
-- RV_STAGE_PLUGINS_MOVIEFORMATS_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/MovieFormats
-- RV_STAGE_PLUGINS_MU_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/Mu
-- RV_STAGE_PLUGINS_NODES_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/Nodes
-- RV_STAGE_PLUGINS_OIIO_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/OIIO
-- RV_STAGE_PLUGINS_PACKAGES_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/Packages
-- RV_STAGE_PLUGINS_PROFILES_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/Profiles
-- RV_STAGE_PLUGINS_PYTHON_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/Python
-- RV_STAGE_PLUGINS_QT_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/Qt
-- RV_STAGE_PLUGINS_SUPPORTFILES_DIR: E:/OpenRV/OpenRV/cmake-build/stage/app/PlugIns/SupportFiles
-- Updating submodules
-- Copying Qt into E:/OpenRV/OpenRV/cmake-build/stage/app
-- Copying Qt translations files ...
-- Copying Qt resources files ...
-- Copying Qt into E:/OpenRV/OpenRV/cmake-build/stage/app -- DONE
-- Populating rv_deps_opentimelineio
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- Configuring done
-- Generating done
-- Build files have been written to: E:/OpenRV/OpenRV/cmake-build/_deps/rv_deps_opentimelineio-subbuild
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Performing update step for 'rv_deps_opentimelineio-populate'
  No patch step for 'rv_deps_opentimelineio-populate'
  No configure step for 'rv_deps_opentimelineio-populate'
  No build step for 'rv_deps_opentimelineio-populate'
  No install step for 'rv_deps_opentimelineio-populate'
  No test step for 'rv_deps_opentimelineio-populate'
  Completed 'rv_deps_opentimelineio-populate'
-- Populating rv_deps_pyside2
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- Configuring done
-- Generating done
-- Build files have been written to: E:/OpenRV/OpenRV/cmake-build/_deps/rv_deps_pyside2-subbuild
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Performing update step for 'rv_deps_pyside2-populate'
  No patch step for 'rv_deps_pyside2-populate'
  No configure step for 'rv_deps_pyside2-populate'
  No build step for 'rv_deps_pyside2-populate'
  No install step for 'rv_deps_pyside2-populate'
  No test step for 'rv_deps_pyside2-populate'
  Completed 'rv_deps_pyside2-populate'
-- Using Boost:        1.76.0
-- Using Dav1d:        1.0.0
-- Using FFMPEG:       n4.4.3
-- Using atomic_ops:   7.7.0
-- Using Imath:        3.1.5
-- Using OpenEXR:      3.1.5
-- Using Python3:      3.9.15
-- Using PySide2:      5.15.2.1
-- Using Qt5:          5.15.2
-- Using zlib:         1.2.13
-- Configuring incomplete, errors occurred!
See also "E:/OpenRV/OpenRV/cmake-build/CMakeFiles/CMakeOutput.log".
`

Here are the last few lines of the CMakeOutput.log

`Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.69


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "E:/OpenRV/OpenRV/cmake-build/CMakeFiles/3.25.2/CompilerIdC/CompilerIdC.exe"

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: E:/OpenRV/OpenRV/cmake-build/CMakeFiles/CMakeScratch/TryCompile-6u26ce

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe cmTC_c5634.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCXXCompilerABI.cpp

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_c5634.dir\Debug\\" /Fd"cmTC_c5634.dir\Debug\vc142.pdb" /external:W1 /Gd /TP /errorReport:queue C:\msys64\mingw64\share\cmake\Modules\CMakeCXXCompilerABI.cpp

  cmTC_c5634.vcxproj -> E:\OpenRV\OpenRV\cmake-build\CMakeFiles\CMakeScratch\TryCompile-6u26ce\Debug\cmTC_c5634.exe




Detecting C compiler ABI info compiled with the following output:
Change Dir: E:/OpenRV/OpenRV/cmake-build/CMakeFiles/CMakeScratch/TryCompile-rralv6

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe cmTC_7053d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCCompilerABI.c

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7053d.dir\Debug\\" /Fd"cmTC_7053d.dir\Debug\vc142.pdb" /external:W1 /Gd /TC /errorReport:queue C:\msys64\mingw64\share\cmake\Modules\CMakeCCompilerABI.c

  cmTC_7053d.vcxproj -> E:\OpenRV\OpenRV\cmake-build\CMakeFiles\CMakeScratch\TryCompile-rralv6\Debug\cmTC_7053d.exe



`

**Comment by geffrak** [comment]
I don't see 
```
CMake Error at cmake/macros/rv_stage.cmake:406 (EXECUTE_PROCESS):
  EXECUTE_PROCESS failed command indexes:

    1: "Child return code: 1"

Call Stack (most recent call first):
  src/plugins/rv-packages/additional_nodes/CMakeLists.txt:11 (RV_STAGE)
```

**Comment by rogernelson** [comment]
I have a feeling it might be this issue which has now been fixed: https://github.com/AcademySoftwareFoundation/OpenRV/pull/31

If you pull/rebase on the latest `main` branch, do you still have the errors?

**Comment by AnhTuWally** [comment]
Hi @rogernelson, I've just found out the issue was because I have my wsl was not properly configured and it lead to "no distribution installed" while trying to execute this. NOTE: I was running MSYS2, I'm not sure why it was trying to run cat in wsl.

```
    EXECUTE_PROCESS(
      COMMAND bash -c "cat ${_package_file} | grep version: | grep --only-matching -e '[0-9.]*'"
      RESULT_VARIABLE _result
      OUTPUT_VARIABLE _pkg_version
      OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    )
```

I uninstalled wsl and it fixed it.
