### ISSUE TITLE
[Bug]: Logging possibly broken

### ISSUE THREAD

**Issue by RyZeePy** [AcademySoftwareFoundation/OpenRV#339]
### What happened?

We have been trying to debug an issue relating to our in-house OCIO Luts and in doing so have ran into an issue with logging. I'm not 100% sure that it's not something on our end but we are not experiencing this issue in our previous build of OpenRV.

Essentially we seem to be losing the ability to output any logging, printing and/or errors through python. During the initialisation of our own MinorMode, printing/logging seems to work fine but as soon as initialisation finishes we can no longer get any output at all. I have tried creating new loggers, handlers and also tried outputting directly through sys.stdout but so far nothing seems to work.
As you can imagine, trying to debug this issue without the ability to output anything becomes quite challenging.

I noticed that a new file logger was added in this commit:
https://github.com/AcademySoftwareFoundation/OpenRV/commit/5d476083effc86acf37670e6fd9c940adc242048

I suspect that this could potentially be the cause of our issues but I am surprised that nobody else has run into this problem yet if it is widespread. Just to note, the log file does not log any of the missing output either. Again, it logs during initialisation of our mode but nothing beyond that.

It'd be great if somebody could check this out and just confirm if it is broken or something on our end we need to look into further.

We built OpenRV from this commit:
https://github.com/AcademySoftwareFoundation/OpenRV/commit/0200db0f9c9aa6c24f80dbdf2b1280e527fcd968

As I mentioned, we're not having this issue using our previous build. Unfortunately I don't have the commit hash for our previous build but it was built around February. We would just use this version but the newer build does have fixes for other issue which we require.

### List all the operating systems versions where this is happening

CentOS 7

### On what computer hardware is this happening?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by geffrak** [comment]
Hi @RyZeePy, thanks for the bug report. We will have a look

**Comment by RyZeePy** [comment]
@geffrak I've just done a new build using the latest commit (aa34e8360edad9be1fe867bce331d5b627784684) and it appears that the logging issue is no longer present. I'm not sure which commit between our last attempt and this new build resolved the issue but I'll close off this ticket now.
