### ISSUE TITLE
Fix link in linux build instructions

### ISSUE THREAD

**Issue by GatesARC** [AcademySoftwareFoundation/OpenRV#38]
The link posted at:
https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/doc/build_system/config_linux_centos7.md#install-devtoolset-9

The link target is not found, even after fixing the ] 
![image](https://user-images.githubusercontent.com/25020253/214981074-f05e3eb3-2769-4d03-9996-153f16de35c4.png)

Thanks!
-Gates

**Comment by rogernelson** [comment]
Thanks @GatesARC.  The link is indeed broken.  Since devtoolset-9 is available from yum now, I recommend just installing it from there with `sudo yum install devtoolset-9`.  I'll update the docs as well.

**Comment by GatesARC** [comment]
Thanks!
