### ISSUE TITLE
[Bug]: Can't select color channel with OCIO enabled

### ISSUE THREAD

**Issue by BrianHanke** [AcademySoftwareFoundation/OpenRV#386]
### What happened?

When viewing an image with OCIO enabled the color channel dropdown is no longer populated. Pressing one of the hotkeys for viewing a channel triggers this error:

![rv](https://github.com/AcademySoftwareFoundation/OpenRV/assets/59420805/fbcbe1af-27da-4188-b221-00b9733d0eff)

### List all the operating systems versions where this is happening

Windows 10

### On what computer hardware is this happening?

Laptop, AMD 4900HS, 16GB RAM, RTX 2060

### Relevant console log output

```shell
INFO: using OCIOFile node for sourceGroup000000_source RVLinearizePipelineGroup
INFO: using OCIODisplay for display:   \\.\DISPLAY1
INFO: C:/onedrive/main_projects/render/commercial/butterfly/close_01.exr
INFO: resetting RVLinearizePipelineGroup for sourceGroup000000_source
INFO: using OCIOFile node for sourceGroup000000_source RVLinearizePipelineGroup
ERROR: event = key-down--r
ERROR: function = __lambda961 (void; Event ignored)
ERROR: Exception Value: exception: "invalid property name @RVDisplayColor.color.channelFlood"
```

### Environment variables

 =::=::\
 ACSetupSvcPort=23210
 ACSvcPort=17532
 ADSK_3DSMAX_STARTUPSCRIPTS_ADDON_DIR=C:\Source\lentil-bhgc\3dsmax
 ADSK_3DSMAX_x64_2024=C:\Program Files\Autodesk\3ds Max 2024\
 ALLUSERSPROFILE=C:\ProgramData
 APPDATA=C:\Users\Brian\AppData\Roaming
 ARNOLD_PLUGIN_PATH=C:\onedrive\Software\maya\scripts\lentil-bhgc\bin
 CARGO_HOME=C:\languages\rust\.cargo
 CommonProgramFiles=C:\Program Files\Common Files
 CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
 CommonProgramW6432=C:\Program Files\Common Files
 COMPUTERNAME=LAPTOP
 ComSpec=C:\Windows\system32\cmd.exe
 CUDA_CACHE_MAXSIZE=4294967296
 DriverData=C:\Windows\System32\Drivers\DriverData
 GOPATH=C:\Users\Brian\go
 GPU_FORCE_64BIT_PTR=0
 GPU_MAX_ALLOC_PERCENT=100
 GPU_MAX_HEAP_SIZE=100
 GPU_SINGLE_ALLOC_PERCENT=100
 GPU_USE_SYNC_OBJECTS=1
 HOME=C:\Users\Brian
 HOMEDRIVE=C:
 HOMEPATH=\Users\Brian
 INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
 IOCIN_ARGS= --format RGB8_PLANAR --useChromaticities 0 --ioSize 61440 --ioMethod 1 --ioMaxAsync 16
 IODPX_ARGS= --format RGB8_PLANAR --useChromaticities 0 --ioSize 61440 --ioMethod 1 --ioMaxAsync 16
 IOEXR_ARGS= --rgbaOnly 0 --inherit 1 --noOneChannel 0 --readWindowIsDisplayWindow 0 --readWindow 3 --planar3channel 0 --stripAlpha 0 --convertYRYBY 0 --ioSize 61440 --ioMethod 3 --ioMaxAsync 16
 IOJPEG_ARGS= --ioSize 61440 --ioMethod 1 --ioMaxAsync 16
 IOTARGA_ARGS= --ioSize 61440 --ioMethod 1 --ioMaxAsync 16
 IOTIFF_ARGS= --ioSize 61440 --ioMethod 1
 LANG=C
 LC_ALL=C
 LOCALAPPDATA=C:\Users\Brian\AppData\Local
 LOGONSERVER=\\LAPTOP
 MARI_MAX_WRITE_PENDING_SIZE_FACTOR=0.75
 MOVIEFFMPEG_ARGS= --defaultFPS 24
 MOVIEMISTIKA_ARGS= --format RGB8_PLANAR
 MTOA_TEMPLATES_PATH=C:\onedrive\Software\maya\scripts\lentil-bhgc\ae
 MU_MODULE_PATH=C:/Users/Brian/AppData/Roaming/RV/Mu;C:/onedrive/Software/open-rv/plugins/Mu
 NUMBER_OF_PROCESSORS=16
 NVIDIAWHITELISTED=0x01
 OCIO=C:\onedrive\main_projects\data\ocio\bhgc_v2.ocio
 OIIO_LIBRARY_PATH=C:/Users/Brian/AppData/Roaming/RV/OIIO;C:/onedrive/Software/open-rv/plugins/OIIO;C:/onedrive/Software/open-rv/plugins/OIIO
 OneDrive=C:\onedrive
 OneDriveConsumer=C:\onedrive
 ORIGINALLOCAL=en
 OS=Windows_NT
 OTIO_PLUGIN_MANIFEST_PATH=C:\onedrive\Software\open-rv\PlugIns\Python\..\SupportFiles\otio_reader\manifest.json
 Path=C:\onedrive\Software\open-rv\lib\site-packages\PySide2;C:/onedrive/Software/open-rv/bin;C:\onedrive\Software\open-rv\bhgc;C:\languages\zig;C:\Program Files\Erlang OTP\bin;C:\Program Files\Elixir\bin;C:\languages\lua;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64;C:\onedrive\Software\OpenImageIO;C:\onedrive\Software\ffmpeg\bin;C:\Python\Python311;C:\Python\Python311\Scripts;C:\onedrive\Software\open-rv\bin;C:\Program Files\ImageMagick;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\7-Zip;C:\onedrive\Scripts\;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Go\bin;C:\Program Files\nodejs\;C:\languages\rust\.cargo\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x86;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x86;C:\Program Files (x86)\Windows Kits\10\bin\\x86;C:\Users\Brian\AppData\Local\Programs\Microsoft VS Code\bin
 PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
 PROCESSOR_ARCHITECTURE=AMD64
 PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
 PROCESSOR_LEVEL=23
 PROCESSOR_REVISION=6001
 ProgramData=C:\ProgramData
 ProgramFiles=C:\Program Files
 ProgramFiles(x86)=C:\Program Files (x86)
 ProgramW6432=C:\Program Files
 PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
 PUBLIC=C:\Users\Public
 PYTHONHOME=C:/onedrive/Software/open-rv
 PYTHONPATH=C:/onedrive/Software/open-rv/lib;C:/onedrive/Software/open-rv/lib/lib-dynload;C:/Users/Brian/AppData/Roaming/RV/Python;C:/onedrive/Software/open-rv/plugins/Python;C:/onedrive/Software/open-rv/plugins/MediaLibrary
 QT_D3DCREATE_MULTITHREADED=1
 QT_QUICK_BACKEND=software
 RlsSvcPort=22112
 RV_APP_INIT=C:/onedrive/Software/open-rv/scripts/rv/rvrc.mu
 RV_APP_PYINIT=C:/onedrive/Software/open-rv/scripts/rv/rvrc.py
 RV_APP_RV=C:/onedrive/Software/open-rv/bin/rv.exe
 RV_APP_RV_SHORT_NAME=rv
 RV_APP_RVIO=C:/onedrive/Software/open-rv/bin/rvio.exe
 RV_DARK=1
 SESSIONNAME=Console
 SHIM_MCCOMPAT=0x800000001
 SSL_CERT_FILE=C:\onedrive\Software\open-rv\lib\site-packages\certifi\cacert.pem
 SystemDrive=C:
 SystemRoot=C:\Windows
 TEMP=C:\Users\Brian\AppData\Local\Temp
 TMP=C:\Users\Brian\AppData\Local\Temp
 TWK_APP_SUPPORT_PATH=C:/Users/Brian/AppData/Roaming/RV;C:/onedrive/Software/open-rv/plugins
 TWK_APP_VERSION=2.0.0
 TWK_FB_PLUGIN_PATH=C:/Users/Brian/AppData/Roaming/RV/ImageFormats;C:/onedrive/Software/open-rv/plugins/ImageFormats
 TWK_MEDIA_LIBRARY_PLUGIN_PATH=C:/onedrive/Software/open-rv/plugins/MediaLibrary
 TWK_MOVIE_PLUGIN_PATH=C:/Users/Brian/AppData/Roaming/RV/MovieFormats;C:/onedrive/Software/open-rv/plugins/MovieFormats
 TWK_NODE_PLUGIN_PATH=C:/Users/Brian/AppData/Roaming/RV/Nodes;C:/onedrive/Software/open-rv/plugins/Nodes
 TWK_OUTPUT_PLUGIN_PATH=C:/onedrive/Software/open-rv/plugins/Output
 TWK_PROFILE_PLUGIN_PATH=C:/Users/Brian/AppData/Roaming/RV/Profiles;C:/onedrive/Software/open-rv/plugins/Profiles
 USERDOMAIN=LAPTOP
 USERDOMAIN_ROAMINGPROFILE=LAPTOP
 USERNAME=Brian
 USERPROFILE=C:\Users\Brian
 VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
 VRAY_FOR_MAYA2024_PLUGINS=C:\Program Files\Chaos Group\V-Ray\Maya 2024 for x64\maya_vray/vrayplugins
 VRAY_GPU_PLATFORMS=nvidia cuda nvidia geforce rtx 2060 with max-q design gpu index0 #rtx_api;
 VRAY_SEND_FEEDBACK=0
 windir=C:\Windows
**************** Build Info ************************
 OS:       WINDOWS
 Arch:     IA32_64
 Compiler: MSVC
*****************************************************

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mike-frank** [comment]
Hi Brian - I remember running into this while implementing OCIO for RV at my last studio. There is a specific package to enable -  `Color Channel Selection` should be in the base list of packages. Enabling should restore r, g, b, a etc.

https://community.shotgridsoftware.com/t/rv-loses-channels-when-enabling-ocio/15181

**Comment by BrianHanke** [comment]
@mike-frank Ah, thanks so much, that works! I was just wondering about this last night.
