### ISSUE TITLE
Build Error for Centos 7

### ISSUE THREAD

**Issue by MuruganChandrasekar** [AcademySoftwareFoundation/OpenRV#4]
I'm Getting Build error at the step: [Configure](https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/doc/build_system/config_linux_centos7.md#configure).

Please find the attached logs here.
[build_error.txt](https://github.com/AcademySoftwareFoundation/OpenRV/files/10456399/build_error.txt)

**Comment by compaga** [comment]
Hi,
As per the instructions, Open RV requires Qt 5.15.2. This may be the cause of your issue.
