### ISSUE TITLE
Error compiling WIN11

### ISSUE THREAD

**Issue by pushpop** [AcademySoftwareFoundation/OpenRV#41]
when i try building OpenRV it gives an error on CMAKE

```
CMake Error at cmake/macros/rv_stage.cmake:406 (EXECUTE_PROCESS):
  EXECUTE_PROCESS failed command indexes:

    1: "Child return code: 1"

Call Stack (most recent call first):
  src/plugins/rv-packages/additional_nodes/CMakeLists.txt:11 (RV_STAGE)
```
can i get help please, thank you

**Comment by geffrak** [comment]
It looks like the same situation as https://github.com/AcademySoftwareFoundation/OpenRV/issues/32. I will be closing the issue because there's a resolution. Please re-open the issue if the resolution needs to be better for you.
