### ISSUE TITLE
CMake Error - Qt5WebEngineCore

### ISSUE THREAD

**Issue by travisbutton** [AcademySoftwareFoundation/OpenRV#42]
Have managed to google my way through majority of the errors I've encountered so far but this is one I can't seem to figure out. I have already installed the MSYS2 pacman qt5 package in addition to all the others listed in the directions which eliminated some other errors I was running into.

Additionally it appears that there was a missing step for invoking CMake which needs to happen from the OpenRV repo rather than root or c:/

Here is the error I'm currently experiencing as well as attaching the CMakeOutput.log:

```
CMake Error at C:/msys64/mingw64/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5WebEngineCore"
  with any of the following names:

    Qt5WebEngineCoreConfig.cmake
    qt5webenginecore-config.cmake

  Add the installation prefix of "Qt5WebEngineCore" to CMAKE_PREFIX_PATH or
  set "Qt5WebEngineCore_DIR" to a directory containing one of the above
  files.  If "Qt5WebEngineCore" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  cmake/dependencies/qt5.cmake:50 (FIND_PACKAGE)
  cmake/dependencies/CMakeLists.txt:36 (INCLUDE)


-- Configuring incomplete, errors occurred!
See also "C:/OpenRV/cmake-build/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: rv.vcxproj
CMake Error: Error processing file: C:/OpenRV/cmake-build/cmake_install.cmake
```

[CMakeOutput.log](https://github.com/AcademySoftwareFoundation/OpenRV/files/10522495/CMakeOutput.log)

**Comment by rogernelson** [comment]
Hi @travisbutton.  The issue is occurring because the pacman Qt5 does not install the webengine (this is because QtWebEngine has not been ported to msys, it only builds with MSVC on Windows).  Unfortunately the only solution is to download and install Qt.

**Comment by travisbutton** [comment]
@rogernelson Thanks so much for the quick reply. I installed Qt as the second step and only installed further through pacman after running into other errors related to Qt in the process. There are endless options on the Qt installer, I just used the default settings originally. Do you guys recommend something specifically, and if so, can you please advise and potentially add it to the instructions for people like myself who aren't familiar with Qt out of this context?

**Comment by geffrak** [comment]
I suggest grabbing everything except android, ios, logs, sources and web assembly. Check Qt Creator under the Developer and Designer Tools on Windows for extra build tools required to build some third parties.

This is a screenshot from my Mac, but it should look similar on Windows.
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/6785406/215200360-f5f2e8ae-7b58-48ec-8be6-67d165a078b4.png">

**Comment by travisbutton** [comment]
Thanks @geffrak. Very useful.
