### ISSUE TITLE
Unable to write settings

### ISSUE THREAD

**Issue by BrianHanke** [AcademySoftwareFoundation/OpenRV#53]
When using a default build of OpenRV it can't write the preferences file in its default location, C:\Users\Brian\Application Data in my case. 

Reading up on it, it seems that folder is deprecated in Windows 10. 

I had a quick look at the code in \src\lib\app\RvCommon\RvApplication.cpp and thought changing

```
#elif defined(PLATFORM_WINDOWS)
        QString config(home + "/Application Data");
```

to something like

```
#elif defined(PLATFORM_WINDOWS)
        QString config(home + "/AppData");
```

should fix the problem. I might build again with this change to see if it works, but thought I'd mention it here too. For now I'm just using a custom pref path, but it would be better if it worked by default. Thanks!

**Comment by BrianHanke** [comment]
@bernie-laberge I got an error launching RV on my laptop saying it couldn't write settings to the Application Data prefs file. The same thing happened when I demoed commercial RV a while ago. It doesn't happen on my desktop though, go figure!

**Comment by bernie-laberge** [comment]
Closing issue as the fix for this issue was merged: https://github.com/AcademySoftwareFoundation/OpenRV/pull/55

**Comment by bernie-laberge** [comment]
Closing issue as the fix for this issue was merged: https://github.com/AcademySoftwareFoundation/OpenRV/pull/55
Thank you @BrianHanke !
