### ISSUE TITLE
[Bug]: OpenJpeg missing from windows build

### ISSUE THREAD

**Issue by richardssam** [AcademySoftwareFoundation/OpenRV#595]
### What happened?

I'm unable to open j2c or j2k files in openRV, even though the library is built. I suspect there is a build error, since while I see the library being built, it doesnt seem to be installed.

### List all the operating systems versions where this is happening

windows 10

### On what computer hardware is this happening?

thinkpad 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cedrik-fuoco-adsk** [comment]
@richardssam I tested with some J2k files and they are displayed. Could you re-build Open RV from main and confirm that it works for you? Thanks!

**Comment by richardssam** [comment]
I'll try and rebuild on windows following your new instructions, it must be
some subtlety that I missed.

Thanks for looking at this.

Sam.

**Comment by cedrik-fuoco-adsk** [comment]
Sorry, I wasn't clear. There was an issue. I just merged the PR that fix the issue. #596 @richardssam

**Comment by richardssam** [comment]
Thanks, that makes me feel much better ;)
