### ISSUE TITLE
Add libarg to repo

### ISSUE THREAD

**Issue by tjjackson** [AcademySoftwareFoundation/OpenRV#63]
I have been tracking down a number of libraries not called out in the CentOS7 build requirements, most have been simple enough to just install.  One that has tripped me up is there are a number of includes to "arg.h", which I was able to track down to Paul Heckbert's libarg written at Carnegie Mellon, with the latest release being from 1998:

https://www.cs.cmu.edu/afs/cs/Web/People/ph/859E/src/libarg/

As one might expect, trying to build C code written in the 1990's doesn't work out of the box with modern compilers.  I presume that Autodesk has an updated in-house version that works with gcc-9?  Would it be possible to add this to the repo?  Or is there some updated version of libarg elsewhere that we just need to install?

**Comment by geffrak** [comment]
It is in the src/pub submodule. Have you pulled the code recursively with "git clone --recursive"? Otherwise you can "git submodule update --init --recursive" to pull the submodules.

**Comment by tjjackson** [comment]
Well, I apparently was playing on "hard mode"!  Things seem to be working now that I cloned the other repos via the --recursive flag.

**Comment by geffrak** [comment]
Closing the issue as the issue seems resolved. Please re-open if I'm wrong.
