### ISSUE TITLE
macOS build fails at PySide / libshiboken2

### ISSUE THREAD

**Issue by ggarra13** [AcademySoftwareFoundation/OpenRV#7]
Installed with Qt's latest 5.12.12 offline installer (online installer could not be found).

Here's the stack trace:

[ 48%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/sourcelocation.cpp.o
[ 50%] Building CXX object libshiboken/CMakeFiles/libshiboken.dir/signature/signature_extend.cpp.o
[ 51%] Building CXX object libshiboken/CMakeFiles/libshiboken.dir/signature/signature_helper.cpp.o
In file included from /Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetalang.cpp:31:
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:46:5: error: unknown type name 'Q_DISABLE_COPY_MOVE'
    Q_DISABLE_COPY_MOVE(QPropertySpec)
    ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:46:39: error: expected ';' at end of declaration list
    Q_DISABLE_COPY_MOVE(QPropertySpec)
                                      ^
                                      ;
In file included from /Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetabuilder.cpp:31:
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:46:5: error: unknown type name 'Q_DISABLE_COPY_MOVE'
    Q_DISABLE_COPY_MOVE(QPropertySpec)
    ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:46:39: error: expected ';' at end of declaration list
    Q_DISABLE_COPY_MOVE(QPropertySpec)
                                      ^
                                      ;
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetabuilder.cpp:2948:47: error: no member named 'endl' in namespace 'Qt'; did you mean simply 'endl'?
        s << QString(72, QLatin1Char('*')) << Qt::endl;
                                              ^~~~~~~~
                                              endl
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:260:28: note: 'endl' declared here
Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetabuilder.cpp:2981:14: error: no member named 'endl' in namespace 'Qt'; did you mean simply 'endl'?
        s << Qt::endl;
             ^~~~~~~~
             endl
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:260:28: note: 'endl' declared here
Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetabuilder.cpp:2987:39: error: no member named 'endl' in namespace 'Qt'; did you mean simply 'endl'?
            s << " - " << it.key() << Qt::endl;
                                      ^~~~~~~~
                                      endl
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:260:28: note: 'endl' declared here
Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetabuilder.cpp:2990:47: error: no member named 'endl' in namespace 'Qt'; did you mean simply 'endl'?
        s << QString(72, QLatin1Char('*')) << Qt::endl << Qt::endl;
                                              ^~~~~~~~
                                              endl
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:260:28: note: 'endl' declared here
Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/abstractmetabuilder.cpp:2990:59: error: no member named 'endl' in namespace 'Qt'; did you mean simply 'endl'?
        s << QString(72, QLatin1Char('*')) << Qt::endl << Qt::endl;
                                                          ^~~~~~~~
                                                          endl
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:260:28: note: 'endl' declared here
Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                           ^
In file included from /Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.cpp:29:
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:46:5: error: unknown type name 'Q_DISABLE_COPY_MOVE'
    Q_DISABLE_COPY_MOVE(QPropertySpec)
    ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:46:39: error: expected ';' at end of declaration list
    Q_DISABLE_COPY_MOVE(QPropertySpec)
                                      ^
                                      ;
[ 53%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/typeparser.cpp.o
[ 54%] Building CXX object libshiboken/CMakeFiles/libshiboken.dir/sbknumpyarrayconverter.cpp.o
2 errors generated.
make[6]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/abstractmetalang.cpp.o] Error 1
make[6]: *** Waiting for unfinished jobs....
[ 56%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/typesystem.cpp.o
7 errors generated.
make[6]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/abstractmetabuilder.cpp.o] Error 1
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.cpp:44:16: error: out-of-line definition of 'QPropertySpec' does not match any declaration in 'QPropertySpec'
QPropertySpec::QPropertySpec(const TypeSystemProperty &ts,
               ^~~~~~~~~~~~~
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.cpp:93:67: error: no member named 'SkipEmptyParts' in namespace 'Qt'
    auto propertyTokens = declaration.split(QLatin1Char(' '), Qt::SkipEmptyParts);
                                                              ~~~~^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.cpp:177:17: error: no matching constructor for initialization of 'QPropertySpec'
     return new QPropertySpec(ts, type);
                ^             ~~~~~~~~
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:43:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class QPropertySpec
      ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/propertyspec.h:43:7: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
5 errors generated.
make[6]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/propertyspec.cpp.o] Error 1
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/typesystem.cpp:513:26: error: no member named 'hex' in namespace 'Qt'; did you mean simply 'hex'?
    d << "modifiers=" << Qt::hex << Qt::showbase << modifiers << Qt::noshowbase << Qt::dec;
                         ^~~~~~~
                         hex
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:239:28: note: 'hex' declared here
Q_CORE_EXPORT QTextStream &hex(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/typesystem.cpp:513:37: error: no member named 'showbase' in namespace 'Qt'; did you mean simply 'showbase'?
    d << "modifiers=" << Qt::hex << Qt::showbase << modifiers << Qt::noshowbase << Qt::dec;
                                    ^~~~~~~~~~~~
                                    showbase
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:241:28: note: 'showbase' declared here
Q_CORE_EXPORT QTextStream &showbase(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/typesystem.cpp:513:66: error: no member named 'noshowbase' in namespace 'Qt'; did you mean simply 'noshowbase'?
    d << "modifiers=" << Qt::hex << Qt::showbase << modifiers << Qt::noshowbase << Qt::dec;
                                                                 ^~~~~~~~~~~~~~
                                                                 noshowbase
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:244:28: note: 'noshowbase' declared here
Q_CORE_EXPORT QTextStream &noshowbase(QTextStream &s);
                           ^
/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/sources/shiboken2/ApiExtractor/typesystem.cpp:513:84: error: no member named 'dec' in namespace 'Qt'; did you mean simply 'dec'?
    d << "modifiers=" << Qt::hex << Qt::showbase << modifiers << Qt::noshowbase << Qt::dec;
                                                                                   ^~~~~~~
                                                                                   dec
/Users/gga/Qt5.12.12/5.12.12/clang_64/lib/QtCore.framework/Headers/qtextstream.h:238:28: note: 'dec' declared here
Q_CORE_EXPORT QTextStream &dec(QTextStream &s);
                           ^
[ 57%] Linking CXX shared library libshiboken2.cpython-39-darwin.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -Wall -fvisibility=hidden -Wno-strict-aliasing -D QT_NO_CAST_FROM_ASCII -D QT_NO_CAST_TO_ASCII -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 5.15.0 -current_version 5.15.2 -o libshiboken2.cpython-39-darwin.5.15.2.1.dylib -install_name @rpath/libshiboken2.cpython-39-darwin.5.15.dylib CMakeFiles/libshiboken.dir/basewrapper.cpp.o CMakeFiles/libshiboken.dir/debugfreehook.cpp.o CMakeFiles/libshiboken.dir/gilstate.cpp.o CMakeFiles/libshiboken.dir/helper.cpp.o CMakeFiles/libshiboken.dir/sbkarrayconverter.cpp.o CMakeFiles/libshiboken.dir/sbkconverter.cpp.o CMakeFiles/libshiboken.dir/sbkenum.cpp.o CMakeFiles/libshiboken.dir/sbkmodule.cpp.o CMakeFiles/libshiboken.dir/sbkstring.cpp.o CMakeFiles/libshiboken.dir/sbkstaticstrings.cpp.o CMakeFiles/libshiboken.dir/bindingmanager.cpp.o CMakeFiles/libshiboken.dir/threadstatesaver.cpp.o CMakeFiles/libshiboken.dir/shibokenbuffer.cpp.o CMakeFiles/libshiboken.dir/qapp_macro.cpp.o CMakeFiles/libshiboken.dir/pep384impl.cpp.o CMakeFiles/libshiboken.dir/voidptr.cpp.o CMakeFiles/libshiboken.dir/typespec.cpp.o CMakeFiles/libshiboken.dir/bufferprocs_py37.cpp.o CMakeFiles/libshiboken.dir/signature/signature.cpp.o CMakeFiles/libshiboken.dir/signature/signature_globals.cpp.o CMakeFiles/libshiboken.dir/signature/signature_extend.cpp.o CMakeFiles/libshiboken.dir/signature/signature_helper.cpp.o CMakeFiles/libshiboken.dir/sbknumpyarrayconverter.cpp.o  -undefined dynamic_lookup 
[ 57%] Built target libshiboken
4 errors generated.
make[6]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/typesystem.cpp.o] Error 1
make[5]: *** [ApiExtractor/CMakeFiles/apiextractor.dir/all] Error 2
make[4]: *** [all] Error 2
error: Error compiling shiboken2
Traceback (most recent call last):
  File "/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/setup.py", line 296, in <module>
    setup_runner.run_setup()
  File "/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/build_scripts/setup_runner.py", line 168, in run_setup
    raise RuntimeError(msg)
RuntimeError: 
setup.py invocation failed with exit code: 1.


setup.py invocation was: /Users/gga/code/applications/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.9 /Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/setup.py install --qmake=/Users/gga/Qt5.12.12/5.12.12/clang_64/bin/qmake --ignore-git --standalone --openssl=/Users/gga/code/applications/OpenRV/cmake-build/RV_DEPS_OPENSSL/install/bin --verbose-build --parallel=16 --internal-build-type=shiboken2

Traceback (most recent call last):
  File "/Users/gga/code/applications/OpenRV/src/build/make_pyside.py", line 283, in <module>
    build()
  File "/Users/gga/code/applications/OpenRV/src/build/make_pyside.py", line 202, in build
    subprocess.run(pyside_build_args).check_returncode()
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['/Users/gga/code/applications/OpenRV/cmake-build/RV_DEPS_PYTHON3/install/bin/python3.9', '-s', '-E', '/Users/gga/code/applications/OpenRV/cmake-build/_deps/rv_deps_pyside2-src/setup.py', 'install', '--qmake=/Users/gga/Qt5.12.12/5.12.12/clang_64/bin/qmake', '--ignore-git', '--standalone', '--openssl=/Users/gga/code/applications/OpenRV/cmake-build/RV_DEPS_OPENSSL/install/bin', '--verbose-build', '--parallel=16']' returned non-zero exit status 1.
make[3]: *** [RV_DEPS_PYTHON3/install/RV_DEPS_PYSIDE2-build-flag] Error 1
make[2]: *** [cmake/dependencies/CMakeFiles/RV_DEPS_PYTHON3-stage-target.dir/all] Error 2
make[1]: *** [src/bin/nsapps/RV/CMakeFiles/RV.dir/rule] Error 2
make: *** [RV] Error 2

**Comment by rogernelson** [comment]
Hi @ggarra13 the errors are due to a macro that was introduced in 5.13, so your Qt version is too old.  The version we test against is 5.15.2.  Hope that helps!

**Comment by ggarra13** [comment]
Thank you.  Sorry for the bother!

**Comment by rogernelson** [comment]
No bother at all! Hope you get the build working!
