### ISSUE TITLE
MacOS build instruction QT directory

### ISSUE THREAD

**Issue by finnschi** [AcademySoftwareFoundation/OpenRV#9]
`cmake -B cmake-build -DCMAKE_BUILD_TYPE=Release -DRV_DEPS_QT5_LOCATION=$HOME/Qt5.15.11/5.15.11/clang_64`

readme tells me to install qt 5.15.2  which defaults installs to 

`/$HOME/Qt/5.15.2/  `

so the command should be

`cmake -B cmake-build -DCMAKE_BUILD_TYPE=Release -DRV_DEPS_QT5_LOCATION=$HOME/Qt/5.15.2/clang_64`

**Comment by NicTanghe** [comment]
Might be in /opt/QT/...

**Comment by finnschi** [comment]
tried on 3 macs  now and it was always in $HOME/Qt/5.15.2/clang_64 by default  using the installer from QT as suggested by the build guide.

**Comment by rogernelson** [comment]
Hi, I agree the path in the build guide should probably be 5.15.2 to match the README.

You can also try sourcing the rvcmds.sh file in the root to setup the build commands for you. 
```
source rvcmds.sh
rvmk
```

Please make sure the paths echoed after you source the rvcmds are correct, and override them with envars if not.

**Comment by etiam** [comment]
did you find a binary installer for 5.15.2 or did you build from source?  i can't seem to find a binary installer anywhere on qt's site?

**Comment by p2or** [comment]
Hi @etiam,

you can run the regular _online installer_ (`qt-unified-macOS...`) and select `5.15.2` in the components section:

<img width="500" alt="Screenshot 2023-01-22 at 09 02 05" src="https://user-images.githubusercontent.com/512368/213906409-cbcf8e43-bdc3-4453-a1e0-eb8e23d5af74.png">

Cheers,
Christian

**Comment by etiam** [comment]
thanks for the info Christian.  i did not see those options in the installer i downloaded (qt-unified-macOS-x64-4.5.1-online.dmg) but after changing the "Selected Categories" to Archive and LTS and waiting awhile i was able to find 5.15.2.  strange.  

<img width="1062" alt="Screenshot 2023-01-22 at 8 27 57 AM" src="https://user-images.githubusercontent.com/193101/213927265-0b5a9579-5812-4ff5-aa45-899e4bc353b4.png">
